export const colorOptions = [
  {
    value: "green-base",
    bgClassName: "bg-green-base",
    borderClassName: "border-green-base",
    lightBgClassName: "bg-green-light",
    textClassName: "text-green-base",
  },
  {
    value: "blue-base",
    bgClassName: "bg-blue-base",
    borderClassName: "border-blue-base",
    lightBgClassName: "bg-blue-light",
    textClassName: "text-blue-base",
  },
  {
    value: "purple-base",
    bgClassName: "bg-purple-base",
    borderClassName: "border-purple-base",
    lightBgClassName: "bg-purple-light",
    textClassName: "text-purple-base",
  },
  {
    value: "pink-base",
    bgClassName: "bg-pink-base",
    borderClassName: "border-pink-base",
    lightBgClassName: "bg-pink-light",
    textClassName: "text-pink-base",
  },
  {
    value: "red-base",
    bgClassName: "bg-red-base",
    borderClassName: "border-red-base",
    lightBgClassName: "bg-red-light",
    textClassName: "text-red-base",
  },
  {
    value: "orange-base",
    bgClassName: "bg-orange-base",
    borderClassName: "border-orange-base",
    lightBgClassName: "bg-orange-light",
    textClassName: "text-orange-base",
  },
  {
    value: "yellow-base",
    bgClassName: "bg-yellow-base",
    borderClassName: "border-yellow-base",
    lightBgClassName: "bg-yellow-light",
    textClassName: "text-yellow-base",
  },
];
